### ISSUE TITLE
all created files have their attributes within MFT entries

### ISSUE THREAD

**Issue by Sim4n6** [dfirlabs/ntfs-specimens#2]
Hi, you know I was a checking the scripts and I pay attention to a little detail. I'm not sure if it is correct ... most of scenarios in the scripts create files residents in the $MFT file ! no file has content more than 700 bytes , so to not fit the $DATA attribute within the MFT entry. don't you think a little example of a such scenario need to be added ?

**Comment by joachimmetz** [comment]
What scenario do think needs to be added?

* non-resident $DATA ? What about https://github.com/dfirlabs/ntfs-specimens/blob/main/generate-specimens-linux.sh#L47
* $ATTRIBUTE_LIST ? What about https://github.com/dfirlabs/ntfs-specimens/blob/main/generate-specimens-behavior-linux.sh#L136

Can you be a bit more specific about what scenario you are missing ?

**Comment by Sim4n6** [comment]
- Indeed, the copy of LICENSE (L47) handles the case of non resident $DATA. my bad !
- but the second provided case (L136) ... I don't know how $ATTRIBUTE_LIST are involved ? because the file created there (testfile1) is a little bit small. did you mean the series of hard-links ? I found this description online : 

> When there are lots of attributes and space in the MFT record is short, all those attributes that can be made non-resident are moved out of the MFT. If there is still not enough room, then an $ATTRIBUTE_LIST attribute is needed. The remaining attributes are placed in a new MFT record and the $ATTRIBUTE_LIST describes where to find them. It is very unusual to see this attribute. 

Were you successful of making an $ATTRIBUTE_LIST by multiple hard-links pointing to the same file ? 

to be more specific, I was thinking at first about a case similar to a one where the content of the file does not fit within the MFT entry, but it is kind of scattered in multiple cluster runs. but I'm not gonna lie to you, I missed the LICENSE copying. 

I'm still learning...  thank you in advance

**Comment by joachimmetz** [comment]
> but the second provided case (L136) ... I don't know how $ATTRIBUTE_LIST are involved ?

The $ATTRIBUTE_LIST is used when there is no space in the MFT entry for all the attributes. So "to not fit the $DATA attribute within the MFT entry" can also be done with forcing an $ATTRIBUTE_LIST to be used. Not only by growing the size of $DATA attribute.

> Were you successful of making an $ATTRIBUTE_LIST by multiple hard-links pointing to the same file ?

Yes

Seeing the original question seems to have been addressed, I'm closing the issue.

**Comment by joachimmetz** [comment]
> the content of the file does not fit within the MFT entry, but it is kind of scattered in multiple cluster runs

Maybe by creating and deleting various small files first and then create a large file?
